In [1]:
import numpy as np

In [4]:
# Q1. (a)
arr = np.array([1,2,3,6,4,5])
print("Original array:", arr)
arr_rev = arr[::-1]
print("Reversed array:", arr_rev)

Original array: [1 2 3 6 4 5]
Reversed array: [5 4 6 3 2 1]


In [5]:
# Q1. (b)
array1 = np.array([[1, 2, 3], [2,4,5], [1,2,3]])
print("Original 2D array:\n", array1)
array1_flat = array1.flatten()
print("Flattened array:", array1_flat)

Original 2D array:
 [[1 2 3]
 [2 4 5]
 [1 2 3]]
Flattened array: [1 2 3 2 4 5 1 2 3]


In [10]:
# Q1. (c)
arr1 = np.array([[1, 2],[3, 4]])
arr2 = np.array([[1,2],[3,4]])
print("Array 1:\n", arr1)
print("Array 2:\n", arr2)
arr_compare = np.array_equal(arr1, arr2)
print("Are both arrays equal?", arr_compare)

Array 1:
 [[1 2]
 [3 4]]
Array 2:
 [[1 2]
 [3 4]]
Are both arrays equal? True


In [15]:
# Q1. (d)
x = np.array([1,2,3,4,5,1,2,1,1,1])
x_most_frequent = np.bincount(x).argmax()
print("Most frequent value in the array x :", x_most_frequent)
x_indices = np.where(x == x_most_frequent)[0]
print("Indices of the most frequent value:", x_indices)

y = np.array([1,1,1,2,3,4,2,4,3,3,])
y_most_frequent = np.bincount(y).argmax()
print("Most frequent value in the array y :", y_most_frequent)
y_indices = np.where(y == y_most_frequent)[0]
print("Indices of the most frequent value:", y_indices)

Most frequent value in the array x : 1
Indices of the most frequent value: [0 5 7 8 9]
Most frequent value in the array y : 1
Indices of the most frequent value: [0 1 2]


In [18]:
# Q1. (e)
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
print("Original array:", gfg)
gfg_sum = np.sum(gfg)
print("Sum of all elements in the array:", gfg_sum)
gfg_sumrowwise = np.sum(gfg, axis=1)
print("Sum of elements row-wise:", gfg_sumrowwise)
gfg_sumcolwise = np.sum(gfg, axis=0)
print("Sum of elements column-wise:", gfg_sumcolwise)

Original array: [[ 4  1  9]
 [12  3  1]
 [ 4  5  6]]
Sum of all elements in the array: 45
Sum of elements row-wise: [[14]
 [16]
 [15]]
Sum of elements column-wise: [[20  9 16]]


In [23]:
# Q1. (f)
n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]])
n_array_sumdiagonal = np.trace(n_array)
print("Sum of diagonal elements:", n_array_sumdiagonal)
n_array_eigenvalue = np.linalg.eigvals(n_array)
print("Eigenvalues of the array:", n_array_eigenvalue)
n_array_eigenvector = np.linalg.eig(n_array)
print("Eigenvectors of the array:\n", n_array_eigenvector[1])
n_array_inverse = np.linalg.inv(n_array)
print("Inverse of the array:\n", n_array_inverse)
n_array_determinant = np.linalg.det(n_array)
print("Determinant of the array:", n_array_determinant)

Sum of diagonal elements: 176
Eigenvalues of the array: [98.16835147 28.097044   49.73460452]
Eigenvectors of the array:
 [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
Inverse of the array:
 [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
Determinant of the array: 137180.0000000001


In [26]:
# Q1. (g)
p = [[1, 2], [2, 3]]
q = [[4, 5], [6, 7]]
multiplication_result = np.dot(p, q)
print("Result of matrix multiplication:\n", multiplication_result)
covariance_matrix = np.cov(p)
print("Covariance matrix of p:\n", covariance_matrix)

p = [[1, 2], [2, 3], [4, 5]]
q = [[4, 5, 1], [6, 7, 2]]
multiplication_result = np.dot(p, q)
print("Result of matrix multiplication:\n", multiplication_result)
covariance_matrix = np.cov(p)
print("Covariance matrix of p:\n", covariance_matrix)

Result of matrix multiplication:
 [[16 19]
 [26 31]]
Covariance matrix of p:
 [[0.5 0.5]
 [0.5 0.5]]
Result of matrix multiplication:
 [[16 19  5]
 [26 31  8]
 [46 55 14]]
Covariance matrix of p:
 [[0.5 0.5 0.5]
 [0.5 0.5 0.5]
 [0.5 0.5 0.5]]


In [30]:
# Q1. (h)
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])
inner_product = np.inner(x, y)
print("Inner product of x and y:\n", inner_product)
outer_product = np.outer(x, y)
print("Outer product of x and y:\n", outer_product)
cartesian_product = np.array(np.meshgrid(x, y)).T.reshape(-1, x.shape[1] + y.shape[1])
print("Cartesian product of x and y:\n", cartesian_product)

Inner product of x and y:
 [[17 52]
 [13 62]]
Outer product of x and y:
 [[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
Cartesian product of x and y:
 [[ 2  1  2  5  2  0]
 [ 2  5  2 10  2  3]
 [ 3  1  3  5  3  0]
 [ 3  5  3 10  3  3]
 [ 4  1  4  5  4  0]
 [ 4  5  4 10  4  3]
 [ 3  1  3  5  3  0]
 [ 3  5  3 10  3  3]
 [ 2  1  2  5  2  0]
 [ 2  5  2 10  2  3]
 [ 9  1  9  5  9  0]
 [ 9  5  9 10  9  3]]


In [34]:
# Q2. (a)
array = np.array([[1, -2, 3],[-4, 5, -6]])
absolute_array = np.abs(array)
print("Absolute array:\n", absolute_array)

flatten_percentiles = np.percentile(array.flatten(), [25, 50, 75])
print("25th, 50th, and 75th percentiles of the flattened array:", flatten_percentiles)

mean_value = np.mean(array)
print("Mean value of the array:", mean_value)
median_value = np.median(array)
print("Median value of the array:", median_value)
std_deviation = np.std(array)
print("Standard deviation of the array:", std_deviation)

Absolute array:
 [[1 2 3]
 [4 5 6]]
25th, 50th, and 75th percentiles of the flattened array: [-3.5 -0.5  2.5]
Mean value of the array: -0.5
Median value of the array: -0.5
Standard deviation of the array: 3.8622100754188224


In [39]:
# Q2. (b)
a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0])
a_floor = np.floor(a)
print("Floor values of a:", a_floor)
a_ceil = np.ceil(a)
print("Ceil values of a:", a_ceil)
a_truncate = np.trunc(a)
print("Truncated values of a:", a_truncate)
a_rounded = np.round(a)
print("Rounded values of a:", a_rounded)


Floor values of a: [-2. -2. -1.  0.  1.  1.  3.]
Ceil values of a: [-1. -1. -0.  1.  2.  2.  3.]
Truncated values of a: [-1. -1. -0.  0.  1.  1.  3.]
Rounded values of a: [-2. -2. -0.  0.  2.  2.  3.]


In [43]:
# Q3. (a)
array = np.array([10, 52, 62, 16, 16, 54, 453])
array_sorted = np.sort(array)
print("Sorted array:", array_sorted)

array_indicesofsortedarray = np.argsort(array)
print("Indices of the sorted array:", array_indicesofsortedarray)

array_4smallestelements = np.partition(array, 4)[:4]
print("4 smallest elements in the array:", array_4smallestelements)

array_5largestelements = np.partition(array, -5)[-5:]
print("5 largest elements in the array:", array_5largestelements)

Sorted array: [ 10  16  16  52  54  62 453]
Indices of the sorted array: [0 3 4 1 5 2 6]
4 smallest elements in the array: [10 16 16 52]
5 largest elements in the array: [ 16  52  54  62 453]
